### ISSUE TITLE
Forms for user account editing & lockbox partner edits

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#196]
- As a user (regardless of whether or not I'm an admin or partner user), I should be able to update my name and my password.
- As a partner, I should be able to update my organization's name and address/contact info.
- Currently the forms to update my user account and my organization's info exist within the nav... this is substantially more difficult than being able to edit this from a separate page

(Ticket was created based on discussion around #153 and #xxx)

**Comment by gujacq** [comment]
For lockbox partner: 

Here's the account information editing on a separate page from the nav drawer - https://invis.io/9EMYOUG7ZBA#/379758093_dashboard_-_Partner_User_-edit_Address-

Here's the password update on a sep page from the nav drawer - https://invis.io/9EMYOUG7ZBA#/379757936_dashboard_-_Partner_User_-update_Password-

Diagram:
<img width="942" alt="Screen Shot 2019-09-15 at 4 53 00 PM" src="https://user-images.githubusercontent.com/33872753/64928144-cb49d780-d7d9-11e9-89a5-2a56fd051ee7.png">

**Comment by gujacq** [comment]
For MAC user (noticed that the sep page doesn't have the horizontal menu because it's not tied to any particular client partner):

Account info on a sep page - https://invis.io/9EMYOUG7ZBA#/384004845_dashboard_-_MAC_User_-menu_Open_-_Account_Settings-

Password update on a sep page - https://invis.io/9EMYOUG7ZBA#/384004844_dashboard_-_MAC_User_-menu_Open_-_Pw_Update-


Notice that the mobile nav displays the horizontal depending on whether they're looking at a current partner fund
<img width="1101" alt="Screen Shot 2019-09-15 at 5 05 33 PM" src="https://user-images.githubusercontent.com/33872753/64928282-727b3e80-d7db-11e9-8b6a-22b6ff117eb1.png">
