### ISSUE TITLE
Do we want to enable devise paranoid mode?

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#21]
@BintLopez look into what this gets us and maybe enable later

_Originally posted by @BintLopez in https://github.com/MidwestAccessCoalition/lockbox_rails/pull/3/review_comment/create_

**Comment by colinxfleming** [comment]
yoooo. paranoid mode is great and is basically a user enumeration attack protection - it basically changes the password reset message from something like 'Sent information to colin@mac.com' to 'if that exists, we sent information to it', a message that doesn't indicate whether that account exists or not.

Here's the exact message you get following DCAF's password reset flow, since we have this turned on:

![image](https://user-images.githubusercontent.com/3866868/71459382-390c8480-2775-11ea-8bfe-7b19511df756.png)

I'll pop up a PR with this.

**Comment by colinxfleming** [comment]
oh just kidding, looks like you all beat me to it per https://github.com/MidwestAccessCoalition/lockbox_rails/blob/master/config/initializers/devise.rb#L84 !

**Comment by BintLopez** [comment]
ooooh yes looks like this issue got duped! thanks for chiming in @colinxfleming!
