### ISSUE TITLE
ready to implement- New user invite email content needs to be tweaked

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#259]
## Context
Currently the new user content is super generic and not customized to the lockbox. This should be customized.

## Process
As a MAC user, invite a partner user to a lockbox
Check the emails

![image](https://user-images.githubusercontent.com/5728859/68553255-3b916580-03e5-11ea-8eae-663f909565ec.png)

## Acceptance Criteria/Definition of Done
this email should be customized to the Lockbox (needs copy)

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by BintLopez** [comment]
@jel535s can you help with copy for this?

**Comment by jel535s** [comment]
_Copy below!_  

A Lockbox account has been created for you, so that you can access Midwest Access Coalition client requests.  BUT!  You still have one vital step you must do, to make your account active.

**ASAP:**  Click the link below to confirm your account, and set up your personal password.  This will only take about 2 minutes. 

Confirm my account [with redirect link]

Here is a very quick walk-through on how to use the Lockbox app [link to https://docs.google.com/document/d/1bhUsBvOoS8E15s8XPrQMejrZONrp-DuZJ42AjPf2odw/edit?usp=sharing].  Please do keep this manual confidential and don't save a copy on your computer, or print it out.  The best way to reference the walk-through in the future is to bookmark the link above, or save this email.

If you have any other questions about how to use this app, or about why your account was created, please forward this email with your questions to lockbox@midwestaccesscoalition.org [mailto: link for this email]

Thank you for all that you do to provide healthcare for those who need it.
