### ISSUE TITLE
Design: Funder users can configure their own email alerts

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#585]
## Context
Currently, all Support Request actions trigger an email to all Funder users from a certain funder, regardless of who created the Support Request. We had a user provide direct feedback that they would like to be able to configure this to only see Support Requests they created.

## Process
On the Edit Profile page, design a new field that will allow Funder users to adjust their email notifications.

Potential wording-
Email Notifications Preference:
I want emails about every Support Request
or 
I only want emails about Support Requests I created.

## Acceptance Criteria/Definition of Done
We have a design mockup that the devs can use to model their work.

## Resources
Current Edit Profile screen in the app:
![image](https://user-images.githubusercontent.com/53353956/112770184-1b1e7700-8feb-11eb-84fa-a630df2ce7d4.png)

**Comment by jasonwynkoop86** [comment]
i think we should combine this ticket with #599
since we are editing the account screen in both tickets. 
added a drop down menu for selecting notifications settings for support requests. 
added 2 menu options. 
Receive All Support Requests Email Notifications
Only Receive Support Request Email Notifications I Created

![image](https://user-images.githubusercontent.com/82782739/119278702-93b94280-bbec-11eb-98c6-3782394ca7d2.png)

saving the option is the same as saving any edits to your account. 
![image](https://user-images.githubusercontent.com/82782739/119278720-b2b7d480-bbec-11eb-86d8-ebaa68c74c32.png)

**Comment by jel535s** [comment]
These designs look great to me! I also noted on the #599 that they may want to reference these designs or even combine the work done there with #586.
